// AUTO-GENERATED by `npm run build:version`. Do not edit by hand.
// Regenerated from packages/mcp-server/package.json#version on every build.
// Mirrors the pattern in packages/cli/src/version.ts (see WP-005).
export const VERSION = "0.0.0";
