// ---------------------------------------------------------------------------
// `chemag completion <shell>`
//
// Prints the shipped completion script for the requested shell (bash | zsh |
// fish). Files are generated by `scripts/gen-completions.ts` at build time
// and copied into `dist/completions/` so the runtime can locate them whether
// running from source (tsx) or from a published install (dist).
//
// Lookup order for the script directory:
//   1. dist-relative   — packages/cli/dist/completions/<shell>.<ext>
//   2. src-relative    — packages/cli/src/completions/<shell>.<ext>      (tsx dev)
//   3. dist-relative-from-commands — packages/cli/dist/commands/.../completions
//
// Errors:
//   - Unknown shell → exit 2 with diagnostic-style message.
//   - Missing script file (build artifact missing) → exit 1 with hint.
// ---------------------------------------------------------------------------

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SUPPORTED_SHELLS = ["bash", "zsh", "fish"] as const;
type Shell = (typeof SUPPORTED_SHELLS)[number];

const FILE_EXT: Record<Shell, string> = {
  bash: "sh",
  zsh: "sh",
  fish: "fish",
};

export function cmdCompletion(argv: string[]): void {
  if (argv.includes("-h") || argv.includes("--help")) {
    console.log(
      "completion — print shell completion script.\n" +
        "Usage: chemag completion <shell>\n" +
        "\n" +
        "Supported shells: bash, zsh, fish\n" +
        "\n" +
        "Install (bash):  chemag completion bash > /etc/bash_completion.d/chemag\n" +
        'Install (zsh):   chemag completion zsh  > "${fpath[1]}/_chemag"\n' +
        "Install (fish):  chemag completion fish > ~/.config/fish/completions/chemag.fish",
    );
    process.exit(0);
  }

  const shell = argv[0];
  if (shell === undefined) {
    console.error("Missing required argument: <shell>");
    console.error("Run 'chemag completion --help' for usage.");
    process.exit(2);
  }
  if (!isShell(shell)) {
    console.error(`Unsupported shell: ${shell}`);
    console.error(`Supported shells: ${SUPPORTED_SHELLS.join(", ")}`);
    process.exit(2);
  }

  const script = readCompletionScript(shell);
  if (script === null) {
    console.error(`Completion script for "${shell}" not found.`);
    console.error(
      "This usually means the package was not built. Run 'pnpm build' in the cli package.",
    );
    process.exit(1);
  }

  process.stdout.write(script);
  if (!script.endsWith("\n")) process.stdout.write("\n");
  process.exit(0);
}

function isShell(value: string): value is Shell {
  return (SUPPORTED_SHELLS as readonly string[]).includes(value);
}

/**
 * Locate and read the completion script for `shell`. Returns null if no copy
 * is found in any of the expected locations.
 *
 * Search order is tolerant of both dist (compiled) and src (tsx) layouts.
 */
function readCompletionScript(shell: Shell): string | null {
  const ext = FILE_EXT[shell];
  const filename = `${shell}.${ext}`;

  const candidates = [
    // packages/cli/dist/commands/completion.js -> ../completions/<file>
    join(__dirname, "..", "completions", filename),
    // packages/cli/src/commands/completion.ts (tsx dev) -> ../completions/<file>
    // (same relative path; both layouts converge here)
    // packages/cli/dist/completions copy if structure differs
    join(__dirname, "..", "..", "completions", filename),
    // packages/cli/src/commands -> ../../src/completions in test runs that
    // import directly from src
    join(__dirname, "..", "completions", filename),
  ];

  for (const p of candidates) {
    if (existsSync(p)) {
      return readFileSync(p, "utf-8");
    }
  }
  return null;
}
