# bash completion for chemag — generated by scripts/gen-completions.ts.
# Do not edit by hand. Re-generate with: pnpm --filter @chemag/cli gen:completions
# shellcheck shell=bash

_chemag() {
  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  local commands="add analyze check check-edit ci completion config emit-rules graph init install-hooks lsp mcp scaffold sync"
  local global_flags="--vocabulary --no-cache --no-telemetry --quiet --help --version"

  if [ "${COMP_CWORD}" -eq 1 ]; then
    # shellcheck disable=SC2207
    COMPREPLY=( $(compgen -W "${commands} ${global_flags}" -- "${cur}") )
    return 0
  fi

  case "${prev}" in
    --vocabulary)
      # shellcheck disable=SC2207
      COMPREPLY=( $(compgen -W "standard chemistry" -- "${cur}") )
      return 0
      ;;
    completion)
      # shellcheck disable=SC2207
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "${cur}") )
      return 0
      ;;
    config)
      # shellcheck disable=SC2207
      COMPREPLY=( $(compgen -W "get set unset" -- "${cur}") )
      return 0
      ;;
  esac

  if [[ "${cur}" == --* ]]; then
    # shellcheck disable=SC2207
    COMPREPLY=( $(compgen -W "${global_flags} --format --dry-run --manifest-only --verbose --explain" -- "${cur}") )
    return 0
  fi

  # Default: complete file paths (workspace.yaml etc).
  # shellcheck disable=SC2207
  COMPREPLY=( $(compgen -f -- "${cur}") )
}

complete -F _chemag chemag
complete -F _chemag chem-ag
