# fish completion for chemag — generated by scripts/gen-completions.ts.
# Do not edit by hand. Re-generate with: pnpm --filter @chemag/cli gen:completions

function __chemag_no_subcommand
  for token in (commandline -opc)[2..-1]
    switch $token
      case add; return 1
      case analyze; return 1
      case check; return 1
      case check-edit; return 1
      case ci; return 1
      case completion; return 1
      case config; return 1
      case emit-rules; return 1
      case graph; return 1
      case init; return 1
      case install-hooks; return 1
      case lsp; return 1
      case mcp; return 1
      case scaffold; return 1
      case sync; return 1
    end
  end
  return 0
end

complete -c chemag -n __chemag_no_subcommand -f -a add -d "add — add a module or unit."
complete -c chem-ag -n __chemag_no_subcommand -f -a add -d "add — add a module or unit."
complete -c chemag -n __chemag_no_subcommand -f -a analyze -d "analyze — check source imports against dependency rules."
complete -c chem-ag -n __chemag_no_subcommand -f -a analyze -d "analyze — check source imports against dependency rules."
complete -c chemag -n __chemag_no_subcommand -f -a check -d "check — validate workspace manifests and filesystem."
complete -c chem-ag -n __chemag_no_subcommand -f -a check -d "check — validate workspace manifests and filesystem."
complete -c chemag -n __chemag_no_subcommand -f -a check-edit -d "Validate a single file edit against module rules."
complete -c chem-ag -n __chemag_no_subcommand -f -a check-edit -d "Validate a single file edit against module rules."
complete -c chemag -n __chemag_no_subcommand -f -a ci -d "Post chemag results to a CI provider's MR/PR review surface."
complete -c chem-ag -n __chemag_no_subcommand -f -a ci -d "Post chemag results to a CI provider's MR/PR review surface."
complete -c chemag -n __chemag_no_subcommand -f -a completion -d "Print shell completion script (bash | zsh | fish)."
complete -c chem-ag -n __chemag_no_subcommand -f -a completion -d "Print shell completion script (bash | zsh | fish)."
complete -c chemag -n __chemag_no_subcommand -f -a config -d "Get or set chem-ag configuration values."
complete -c chem-ag -n __chemag_no_subcommand -f -a config -d "Get or set chem-ag configuration values."
complete -c chemag -n __chemag_no_subcommand -f -a emit-rules -d "emit-rules — generate AI-editor rule files (AGENTS.md, CLAUDE.md, .cursor/rules, .github/copilot-instructions.md, .aider/CONVENTIONS.md, .clinerules) from workspace.yaml."
complete -c chem-ag -n __chemag_no_subcommand -f -a emit-rules -d "emit-rules — generate AI-editor rule files (AGENTS.md, CLAUDE.md, .cursor/rules, .github/copilot-instructions.md, .aider/CONVENTIONS.md, .clinerules) from workspace.yaml."
complete -c chemag -n __chemag_no_subcommand -f -a graph -d "graph — output a Mermaid dependency diagram."
complete -c chem-ag -n __chemag_no_subcommand -f -a graph -d "graph — output a Mermaid dependency diagram."
complete -c chemag -n __chemag_no_subcommand -f -a init -d "init — bootstrap a new workspace."
complete -c chem-ag -n __chemag_no_subcommand -f -a init -d "init — bootstrap a new workspace."
complete -c chemag -n __chemag_no_subcommand -f -a install-hooks -d "install-hooks — install or uninstall AI-editor hook integrations that call chemag check-edit / analyze around tool edits."
complete -c chem-ag -n __chemag_no_subcommand -f -a install-hooks -d "install-hooks — install or uninstall AI-editor hook integrations that call chemag check-edit / analyze around tool edits."
complete -c chemag -n __chemag_no_subcommand -f -a lsp -d "lsp — run a Language Server Protocol server for chemag (stdio)."
complete -c chem-ag -n __chemag_no_subcommand -f -a lsp -d "lsp — run a Language Server Protocol server for chemag (stdio)."
complete -c chemag -n __chemag_no_subcommand -f -a mcp -d "mcp — run an MCP server exposing chemag tools to MCP-aware clients."
complete -c chem-ag -n __chemag_no_subcommand -f -a mcp -d "mcp — run an MCP server exposing chemag tools to MCP-aware clients."
complete -c chemag -n __chemag_no_subcommand -f -a scaffold -d "scaffold — generate stub files from manifests."
complete -c chem-ag -n __chemag_no_subcommand -f -a scaffold -d "scaffold — generate stub files from manifests."
complete -c chemag -n __chemag_no_subcommand -f -a sync -d "sync — generate manifests from existing code."
complete -c chem-ag -n __chemag_no_subcommand -f -a sync -d "sync — generate manifests from existing code."

complete -c chemag -l help -s h -d 'Show help'
complete -c chemag -l version -s v -d 'Show version'
complete -c chemag -l vocabulary -x -a 'standard chemistry' -d 'Vocabulary'
complete -c chemag -l no-cache -d 'Disable manifest/imports cache for this run'
complete -c chemag -l no-telemetry -d 'Disable usage telemetry for this run'
complete -c chemag -l quiet -d 'Suppress spinners and informational output'

complete -c chem-ag -l help -s h -d 'Show help'
complete -c chem-ag -l version -s v -d 'Show version'
complete -c chem-ag -l vocabulary -x -a 'standard chemistry' -d 'Vocabulary'
complete -c chem-ag -l no-cache -d 'Disable manifest/imports cache for this run'
complete -c chem-ag -l no-telemetry -d 'Disable usage telemetry for this run'
complete -c chem-ag -l quiet -d 'Suppress spinners and informational output'

complete -c chemag -n '__fish_seen_subcommand_from completion' -x -a 'bash zsh fish'
complete -c chem-ag -n '__fish_seen_subcommand_from completion' -x -a 'bash zsh fish'
complete -c chemag -n '__fish_seen_subcommand_from config' -x -a 'get set unset'
complete -c chem-ag -n '__fish_seen_subcommand_from config' -x -a 'get set unset'
