#compdef chemag chem-ag
# zsh completion for chemag — generated by scripts/gen-completions.ts.
# Do not edit by hand. Re-generate with: pnpm --filter @chemag/cli gen:completions

_chemag() {
  local -a commands
  commands=( \
    'add:add — add a module or unit.' \
    'analyze:analyze — check source imports against dependency rules.' \
    'check:check — validate workspace manifests and filesystem.' \
    'check-edit:Validate a single file edit against module rules.' \
    'completion:Print shell completion script (bash | zsh | fish).' \
    'config:Get or set chem-ag configuration values.' \
    'emit-rules:emit-rules — generate AI-editor rule files (AGENTS.md, CLAUDE.md, .cursor/rules, .github/copilot-instructions.md, .aider/CONVENTIONS.md, .clinerules) from workspace.yaml.' \
    'graph:graph — output a Mermaid dependency diagram.' \
    'init:init — bootstrap a new workspace.' \
    'mcp:mcp — run an MCP server exposing chemag tools to MCP-aware clients.' \
    'scaffold:scaffold — generate stub files from manifests.' \
    'sync:sync — generate manifests from existing code.' \
  )

  _arguments -C \
    '(--help -h)'{--help,-h}'[Show help]' \
    '(--version -v)'{--version,-v}'[Show version]' \
    '--vocabulary[Vocabulary: standard or chemistry]:vocab:(standard chemistry)' \
    '--no-cache[Disable manifest/imports cache for this run]' \
    '--no-telemetry[Disable usage telemetry for this run]' \
    '--quiet[Suppress spinners and informational output]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
        completion)
          _values 'shell' bash zsh fish
          ;;
        config)
          _values 'op' get set unset
          ;;
        *)
          _files
          ;;
      esac
      ;;
  esac
}

_chemag "$@"
