#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Regenerates packages/mcp-server/src/version.ts from
// packages/mcp-server/package.json#version. Mirror of the WP-005 pattern in
// packages/cli/scripts/build-version.mjs. Run automatically by `prebuild`;
// the output file is committed so `tsc --noEmit` works on a fresh clone.
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(here, "..", "package.json");
const versionPath = resolve(here, "..", "src", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
if (typeof pkg.version !== "string") {
  console.error(`build-version: ${pkgPath} has no string "version" field`);
  process.exit(1);
}

const HEADER = [
  "// AUTO-GENERATED by `npm run build:version`. Do not edit by hand.",
  "// Regenerated from packages/mcp-server/package.json#version on every build.",
  "// Mirrors the pattern in packages/cli/src/version.ts (see WP-005).",
  "",
].join("\n");

const content = `${HEADER}export const VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(versionPath, content, "utf-8");
console.log(`build-version: wrote ${versionPath} (${pkg.version})`);
