// AUTO-GENERATED by `npm run build:version`. Do not edit by hand.
// Regenerated from packages/cli/package.json#version on every build.
//
// Why a generated module?
//   - Avoids `JSON.parse(readFileSync('../../package.json'))` at runtime,
//     which is fragile in compiled `dist/` (relative path varies with the
//     `files` field and tarball layout).
//   - Avoids `import pkg from '../package.json' with { type: 'json' }`,
//     whose emit shape under `module: NodeNext` has churned across TS
//     minors.
//
// CI guard: `packages/cli/test/version.guard.test.ts` asserts that
// `VERSION` here equals `packages/cli/package.json#version` so commits
// can't drift after `npm version <bump>`.
//
// Release flow: the `prebuild` npm script calls `npm run build:version`
// which rewrites this file, and the regenerated content is committed.
export const VERSION = "0.3.0";
