#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Regenerates packages/cli/src/version.ts from packages/cli/package.json#version.
// Run automatically by the `prebuild` npm script. The output file is committed
// to git so a fresh clone type-checks before any build runs; CI guard test
// (packages/cli/test/version.guard.test.ts) catches drift.
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(here, "..", "package.json");
const versionPath = resolve(here, "..", "src", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
if (typeof pkg.version !== "string") {
  console.error(`build-version: ${pkgPath} has no string "version" field`);
  process.exit(1);
}

const HEADER = [
  "// AUTO-GENERATED by `npm run build:version`. Do not edit by hand.",
  "// Regenerated from packages/cli/package.json#version on every build.",
  "//",
  "// Why a generated module?",
  "//   - Avoids `JSON.parse(readFileSync('../../package.json'))` at runtime,",
  "//     which is fragile in compiled `dist/` (relative path varies with the",
  "//     `files` field and tarball layout).",
  "//   - Avoids `import pkg from '../package.json' with { type: 'json' }`,",
  "//     whose emit shape under `module: NodeNext` has churned across TS",
  "//     minors.",
  "//",
  "// CI guard: `packages/cli/test/version.guard.test.ts` asserts that",
  "// `VERSION` here equals `packages/cli/package.json#version` so commits",
  "// can't drift after `npm version <bump>`.",
  "//",
  "// Release flow: the `prebuild` npm script calls `npm run build:version`",
  "// which rewrites this file, and the regenerated content is committed.",
  "",
].join("\n");

const content = `${HEADER}export const VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(versionPath, content, "utf-8");
console.log(`build-version: wrote ${versionPath} (${pkg.version})`);
