// ---------------------------------------------------------------------------
// Build-time completion-script generator.
//
// Walks the citty command tree and emits `bash.sh`, `zsh.sh`, `fish.fish` to
// `packages/cli/src/completions/`. The committed files are checked in; CI's
// drift check re-runs this script and asserts byte-identical output to detect
// stale completions.
//
// We do NOT depend on a citty completion plugin because the citty version we
// pin (^0.2.x) does not ship one. The generator is small and shells out only
// what we need: command names + whether positional arg is "shell" (for the
// completion subcommand).
//
// Run with: `pnpm --filter @chemag/cli tsx scripts/gen-completions.ts`
// or via the workspace-level drift check.
// ---------------------------------------------------------------------------

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { CommandDef } from "citty";
import { buildCommandTree } from "../src/cli-meta.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUT_DIR = resolve(__dirname, "..", "src", "completions");

type Sub = { name: string; description: string };

function collectSubcommands(tree: CommandDef): Sub[] {
  const subs = (tree.subCommands as Record<string, CommandDef> | undefined) ?? {};
  const result: Sub[] = [];
  for (const [name, def] of Object.entries(subs)) {
    const meta = (def.meta as { description?: string }) ?? {};
    result.push({ name, description: (meta.description ?? "").replace(/"/g, "'") });
  }
  return result;
}

function generateBash(subs: Sub[]): string {
  const cmds = subs.map((s) => s.name).join(" ");
  // POSIX-compliant bash completion. Avoids bashisms that shellcheck flags.
  return `# bash completion for chemag — generated by scripts/gen-completions.ts.
# Do not edit by hand. Re-generate with: pnpm --filter @chemag/cli gen:completions
# shellcheck shell=bash

_chemag() {
  local cur prev
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local commands="${cmds}"
  local global_flags="--vocabulary --no-cache --no-telemetry --quiet --help --version"

  if [ "\${COMP_CWORD}" -eq 1 ]; then
    # shellcheck disable=SC2207
    COMPREPLY=( $(compgen -W "\${commands} \${global_flags}" -- "\${cur}") )
    return 0
  fi

  case "\${prev}" in
    --vocabulary)
      # shellcheck disable=SC2207
      COMPREPLY=( $(compgen -W "standard chemistry" -- "\${cur}") )
      return 0
      ;;
    completion)
      # shellcheck disable=SC2207
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "\${cur}") )
      return 0
      ;;
    config)
      # shellcheck disable=SC2207
      COMPREPLY=( $(compgen -W "get set unset" -- "\${cur}") )
      return 0
      ;;
  esac

  if [[ "\${cur}" == --* ]]; then
    # shellcheck disable=SC2207
    COMPREPLY=( $(compgen -W "\${global_flags} --format --dry-run --manifest-only --verbose --explain" -- "\${cur}") )
    return 0
  fi

  # Default: complete file paths (workspace.yaml etc).
  # shellcheck disable=SC2207
  COMPREPLY=( $(compgen -f -- "\${cur}") )
}

complete -F _chemag chemag
complete -F _chemag chem-ag
`;
}

function generateZsh(subs: Sub[]): string {
  const cmdLines = subs.map((s) => `    '${s.name}:${s.description}'`).join(" \\\n");

  return `#compdef chemag chem-ag
# zsh completion for chemag — generated by scripts/gen-completions.ts.
# Do not edit by hand. Re-generate with: pnpm --filter @chemag/cli gen:completions

_chemag() {
  local -a commands
  commands=( \\
${cmdLines} \\
  )

  _arguments -C \\
    '(--help -h)'{--help,-h}'[Show help]' \\
    '(--version -v)'{--version,-v}'[Show version]' \\
    '--vocabulary[Vocabulary: standard or chemistry]:vocab:(standard chemistry)' \\
    '--no-cache[Disable manifest/imports cache for this run]' \\
    '--no-telemetry[Disable usage telemetry for this run]' \\
    '--quiet[Suppress spinners and informational output]' \\
    '1: :->command' \\
    '*::arg:->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
        completion)
          _values 'shell' bash zsh fish
          ;;
        config)
          _values 'op' get set unset
          ;;
        *)
          _files
          ;;
      esac
      ;;
  esac
}

_chemag "$@"
`;
}

function generateFish(subs: Sub[]): string {
  const lines: string[] = [
    "# fish completion for chemag — generated by scripts/gen-completions.ts.",
    "# Do not edit by hand. Re-generate with: pnpm --filter @chemag/cli gen:completions",
    "",
    "function __chemag_no_subcommand",
    "  for token in (commandline -opc)[2..-1]",
    "    switch $token",
  ];
  for (const s of subs) {
    lines.push(`      case ${s.name}; return 1`);
  }
  lines.push("    end");
  lines.push("  end");
  lines.push("  return 0");
  lines.push("end");
  lines.push("");
  // Top-level subcommands
  for (const s of subs) {
    lines.push(
      `complete -c chemag -n __chemag_no_subcommand -f -a ${s.name} -d "${s.description}"`,
    );
    lines.push(
      `complete -c chem-ag -n __chemag_no_subcommand -f -a ${s.name} -d "${s.description}"`,
    );
  }
  // Global flags
  lines.push("");
  lines.push("complete -c chemag -l help -s h -d 'Show help'");
  lines.push("complete -c chemag -l version -s v -d 'Show version'");
  lines.push("complete -c chemag -l vocabulary -x -a 'standard chemistry' -d 'Vocabulary'");
  lines.push("complete -c chemag -l no-cache -d 'Disable manifest/imports cache for this run'");
  lines.push("complete -c chemag -l no-telemetry -d 'Disable usage telemetry for this run'");
  lines.push("complete -c chemag -l quiet -d 'Suppress spinners and informational output'");
  lines.push("");
  // Mirror to chem-ag alias
  lines.push("complete -c chem-ag -l help -s h -d 'Show help'");
  lines.push("complete -c chem-ag -l version -s v -d 'Show version'");
  lines.push("complete -c chem-ag -l vocabulary -x -a 'standard chemistry' -d 'Vocabulary'");
  lines.push("complete -c chem-ag -l no-cache -d 'Disable manifest/imports cache for this run'");
  lines.push("complete -c chem-ag -l no-telemetry -d 'Disable usage telemetry for this run'");
  lines.push("complete -c chem-ag -l quiet -d 'Suppress spinners and informational output'");
  lines.push("");
  // Per-subcommand argument completions
  lines.push(
    "complete -c chemag -n '__fish_seen_subcommand_from completion' -x -a 'bash zsh fish'",
  );
  lines.push(
    "complete -c chem-ag -n '__fish_seen_subcommand_from completion' -x -a 'bash zsh fish'",
  );
  lines.push("complete -c chemag -n '__fish_seen_subcommand_from config' -x -a 'get set unset'");
  lines.push("complete -c chem-ag -n '__fish_seen_subcommand_from config' -x -a 'get set unset'");

  return `${lines.join("\n")}\n`;
}

function main(): void {
  // Use a deterministic version string so generated output is stable across
  // version bumps. The generator output is committed and drift-checked; we do
  // not want every version bump to change the script body.
  const tree = buildCommandTree("0.0.0");
  const subs = collectSubcommands(tree);

  // Sort subs so iteration order is reproducible. defineCommand subCommands
  // is a plain object — insertion order is preserved by V8 but sorting makes
  // generated output independent of source-file order changes.
  subs.sort((a, b) => a.name.localeCompare(b.name));

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, "bash.sh"), generateBash(subs), "utf-8");
  writeFileSync(join(OUT_DIR, "zsh.sh"), generateZsh(subs), "utf-8");
  writeFileSync(join(OUT_DIR, "fish.fish"), generateFish(subs), "utf-8");
  console.log(`Wrote 3 completion scripts to ${OUT_DIR}`);
}

main();
